[project]
name = "science_team"
version = "0.1.0"
description = "science_team using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.2.1",
    "openai",
]

[project.scripts]
science_team = "science_team.main:run"
run_crew = "science_team.main:run"
train = "science_team.main:train"
replay = "science_team.main:replay"
test = "science_team.main:test"
run_with_trigger = "science_team.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
